spring:
  application:
    name: notification-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/picpay?currentSchema=notification
    username: picpay
    password: picpay
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: notification
  flyway:
    enabled: false

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
