spring:
  application:
    name: billing-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/picpay?currentSchema=billing
    username: picpay
    password: picpay
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: billing
  flyway:
    enabled: false

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
