spring:
  application:
    name: token-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/picpay?currentSchema=token
    username: picpay
    password: picpay
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: token
  flyway:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info

vault:
  aes-key: "${VAULT_AES_KEY:YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=}"
